//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentToPArtAssignment
    {
        public int Id { get; set; }
        public int AssignmentId { get; set; }
        public int PartTimeAssignmentId { get; set; }
    
        public virtual Assignments Assignments { get; set; }
        public virtual PartAssignments PartAssignments { get; set; }
    }
}
