//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak_2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VLN2_2016_H38Entities1 : DbContext
    {
        public VLN2_2016_H38Entities1()
            : base("name=VLN2_2016_H38Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<AssignmentToPArtAssignment> AssignmentToPArtAssignment { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<PartAssignment> PartAssignment { get; set; }
        public virtual DbSet<PartAssignments> PartAssignments { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SentInAssignments> SentInAssignments { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersToCourses> UsersToCourses { get; set; }
    }
}
