//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartAssignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartAssignments()
        {
            this.AssignmentToPArtAssignment = new HashSet<AssignmentToPArtAssignment>();
            this.SentInAssignments = new HashSet<SentInAssignments>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ValuePercentage { get; set; }
        public string Description { get; set; }
        public string PathToInputOutputFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentToPArtAssignment> AssignmentToPArtAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentInAssignments> SentInAssignments { get; set; }
    }
}
